# Generated by Django 5.2.15 on 2026-06-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_usagelog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Screenshot',
            new_name='ScreenshotModel',
        ),
        migrations.RenameModel(
            old_name='UsageLog',
            new_name='UsageLogModel',
        ),
    ]
