# Generated by Django 5.2.15 on 2026-06-20 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_rename_screenshot_screenshotmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLimitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')])),
                ('limit_minutes', models.IntegerField(default=0)),
                ('is_unlimited', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_limits', to='devices.devicemodel')),
            ],
            options={
                'unique_together': {('device', 'day_of_week')},
            },
        ),
    ]
